spring:
  application:
    name: platorm
  datasource:
    url: jdbc:mysql://39.104.83.135:3306/smart_agri?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: kaze
    password: 901170119
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 1983517529@qq.com
    password: pmfjlrqfgxpldhfc
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.agri.platform: DEBUG
